# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       pandora-box

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    pandora-box
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    TODO
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  pandora-box.yaml
Requires:   patchmanager
BuildRequires:  pkgconfig(Qt5Core)

%description
The pandora box contains Sailfish OS 
homescreen. Opening it allows patching
it and features tweaking. 

This package contains some tweaks for
lipstick-pandora, that can be used by 
patchmanager.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches
# >> files
# << files
